### ISSUE TITLE
Percent needed to win

### ISSUE THREAD

**Issue by arenius** [open-austin/ballotapi#12]
The measure object should have a column for percent needed to win.  Name ideas are:

threshold
victory_threshold
pass_threshold
percent_needed_to_pass
passing_percentage

I prefer to be as clear as possible so I like percent_needed_to_pass, even if its more verbose.

Thoughts?

**Comment by diafygi** [comment]
Alternatively, since most of the time it's either a 51% or 2/3rds or 3/4ths majority, we could just have three different voting_methods for plurality (`plurality_50`, `plurality_66`, `plurality_75`). Having dedicated parameter for the threshold would probably be called for if we saw a lot of really weird thresholds (maybe more than 20?).

**Comment by diafygi** [comment]
Added "threshold" field to the spec. Need to implement in code.

**Comment by diafygi** [comment]
This is replaced by [`voting_method`](https://ballotapi.org/docs/api/contests#voting_method)
