### ISSUE TITLE
Review API docs

### ISSUE THREAD

**Issue by diafygi** [open-austin/ballotapi#29]
Would love comments on the API docs and overall design of the API.

https://ballotapi.org/docs

**Comment by diafygi** [comment]
Added [Choice.id](https://ballotapi.org/docs/api/contests#choice-object-id) attribute thanks to @lazarus1331

**Comment by dfcoffin** [comment]
Voters may find entering the `coords=` query parameter a bit challenging.  Have you considered supporting `location= or city=` as well and then obtaining the `coords` using Google's Map API?  The API does require an apiKey, and has a limited FREE access, but I suspect since this is an open Source application, Google may be willing to waive the map fee or contribute to the project.  The apiKey could be externally stored so as to protect it's security.

**Comment by diafygi** [comment]
@dfcoffin Thanks for the suggestion. Yes, the reason geocoding isn't in the API is because there aren't any self-hosted public domain options for that, so I'd rather leave it up to the developer to use whatever geocoding resource they want to convert addresses into coordinates (Google Maps, Mapbox, Nominatim, MapQuest, Here, etc.).

In theory you could make a self-hosted public domain geocoding service from Census.gov's [TIGER](https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-geodatabase-file.html) datasets, but that's well outside the scope of this project.

**Comment by mscarey** [comment]
I think the "precinct" object should correspond to real precincts. People might want to search for all elections for a particular precinct, or the first and last elections when a precinct was in existence. And probably you could use the "ocd_id" attribute as the key column. 

For the concept of "the region that shares a common ballot style" I'd be more comfortable having it called "phase" or something else. And it seems like you should try to make the process of creating a "phase" completely automated by merging the other region geometries in your database.

**Comment by diafygi** [comment]
We've been reviewing the API docs at community action nights for over 6 months now, so I think we're good until the prototype is working.
